alertmanager:
  alertmanagerSpec:
    externalUrl: "http://alertmanager.monitoring.svc.cluster.local"  # Internal cluster URL
    routePrefix: "/"
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 2
    alertmanagerConfigMatcherStrategy:
      type: None
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
