alertmanager:
  alertmanagerSpec:
    externalUrl: "http://<LOAD_BALANCER_DNS>/alertmanager"  # Replace <LOAD_BALANCER_DNS> with your actual LB DNS
    routePrefix: /alertmanager  # Explicitly set the route prefix
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 2
    alertmanagerConfigMatcherStrategy:
      type: None
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000

grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true

prometheus:
  prometheusSpec:
    externalUrl: "http://<LOAD_BALANCER_DNS>/prometheus"  # Replace <LOAD_BALANCER_DNS> with your actual LB DNS
    routePrefix: /prometheus  # Explicitly set the route prefix
